query collection($handle: String!) {
	collectionByHandle(handle: $handle) {
		products(first: 250) {
			edges {
				node {
					id
					title
					handle
					priceRange {
						maxVariantPrice {
							amount
							currencyCode
						}
						minVariantPrice {
							amount
							currencyCode
						}
					}
					images(first: 1) {
						edges {
							node {
								originalSrc
								altText
							}
						}
					}
				}
			}
		}
	}
}
