query productByHandle($handle: String!) {
	productByHandle(handle: $handle) {
		id
		title
		handle
		priceRange {
			maxVariantPrice {
				amount
				currencyCode
			}
			minVariantPrice {
				amount
				currencyCode
			}
		}
		images(first: 10) {
			edges {
				cursor
				node {
					originalSrc
					altText
				}
			}
		}
		variants(first: 10) {
			edges {
				node {
					id
					title
					selectedOptions {
						name
						value
					}
					priceV2 {
						amount
						currencyCode
					}
					image {
						originalSrc
					}
				}
			}
		}
	}
}
