query productsByType($query: String!) {
	products(query: $query, first: 250) {
		edges {
			node {
				title
				handle
				priceRange {
					maxVariantPrice {
						amount
						currencyCode
					}
					minVariantPrice {
						amount
						currencyCode
					}
				}
				images(first: 1) {
					edges {
						node {
							originalSrc
							altText
						}
					}
				}
			}
		}
	}
}
