query productsByType($query: String!) {
	products(query: $query, first: 250) {
		edges {
			node {
				id
				title
				handle
				priceRange {
					maxVariantPrice {
						amount
						currencyCode
					}
					minVariantPrice {
						amount
						currencyCode
					}
				}
				images(first: 10) {
					edges {
						node {
							originalSrc
							altText
						}
					}
				}
				variants(first: 10) {
					edges {
						node {
							id
							title
							priceV2 {
								amount
								currencyCode
							}
							image {
								originalSrc
							}
						}
					}
				}
			}
		}
	}
}
